// A list of Pokémon TCG artists, sourced from Bulbapedia and enriched with card counts.
export interface Artist {
  name: string;
  cardCount: number;
}

export const ARTIST_DATA: Artist[] = [
 { name: '0313', cardCount: 42 },
 { name: '5ban Graphics', cardCount: 1729 },
 { name: 'Acorviart', cardCount: 1 },
 { name: 'AKIRA EGAWA', cardCount: 147 },
 { name: 'aky CG Works', cardCount: 242 },
 { name: 'Aliya Chen', cardCount: 14 },
 { name: 'Amelicart', cardCount: 15 },
 { name: 'Anesaki Dynamic', cardCount: 8 },
 { name: 'Apios', cardCount: 1 },
 { name: 'Arai Kiriko', cardCount: 1 },
 { name: 'Asako Ito', cardCount: 128 },
 { name: 'aspara', cardCount: 71 },
 { name: 'Atsuko Nishida', cardCount: 218 },
 { name: 'Atsuko Ujiie', cardCount: 11 },
 { name: 'Atsushi Furusawa', cardCount: 11 },
 { name: 'Atsuya Uki', cardCount: 1 },
 { name: 'Avec Yoko', cardCount: 1 },
 { name: 'Aya Kusube', cardCount: 119 },
 { name: 'Ayaka Yoshida', cardCount: 21 },
 { name: 'AYUMI ODASHIMA', cardCount: 3 },
 { name: 'BERUBURI', cardCount: 25 },
 { name: 'buchi', cardCount: 8 },
 { name: 'Bun Toujo', cardCount: 1 },
 { name: 'burari', cardCount: 1 },
 { name: 'chibi', cardCount: 44 },
 { name: 'cochi8i', cardCount: 1 },
 { name: 'Cona Nitanda', cardCount: 1 },
 { name: 'ConceptLab', cardCount: 5 },
 { name: 'CR CG gangs', cardCount: 25 },
 { name: 'D.A.G Inc.', cardCount: 13 },
 { name: 'Daisuke Ito', cardCount: 38 },
 { name: 'Daisuke Iwamoto', cardCount: 1 },
 { name: 'danciao', cardCount: 1 },
 { name: 'DemizuPosuka', cardCount: 20 },
 { name: 'DOM', cardCount: 19 },
 { name: 'Dsuke', cardCount: 34 },
 { name: 'Ebila', cardCount: 1 },
 { name: 'Emi Ando', cardCount: 4 },
 { name: 'Emi Miwa', cardCount: 1 },
 { name: 'Emi Yoshida', cardCount: 1 },
 { name: 'En Morikura', cardCount: 1 },
 { name: 'Eri Kamei', cardCount: 3 },
 { name: 'Eri Yamaki', cardCount: 1 },
 { name: 'Eske Yoshinob', cardCount: 102 },
 { name: 'Etsuya Hattori', cardCount: 4 },
 { name: 'Felicia Chen', cardCount: 3 },
 { name: 'Framestore', cardCount: 24 },
 { name: 'Fujimoto Gold', cardCount: 1 },
 { name: 'Fumie Kittaka', cardCount: 1 },
 { name: 'GOSSAN', cardCount: 35 },
 { name: 'GOTO minori', cardCount: 14 },
 { name: 'GAME FREAK inc.', cardCount: 5 },
 { name: 'Gakuji Nomoto', cardCount: 1 },
 { name: 'Gapao', cardCount: 4 },
 { name: 'Gemi', cardCount: 13 },
 { name: 'GIDORA', cardCount: 33 },
 { name: 'Gosha', cardCount: 7 },
 { name: 'HAGIYA Kaoru', cardCount: 1 },
 { name: 'HICO KIM', cardCount: 1 },
 { name: 'HYOGONOSUKE', cardCount: 179 },
 { name: 'Hajime Kusajima', cardCount: 115 },
 { name: 'hanabushi', cardCount: 11 },
 { name: 'Haru Akasaka', cardCount: 17 },
 { name: 'Haruko Ichikawa', cardCount: 2 },
 { name: 'Hasegawa Saki', cardCount: 12 },
 { name: 'Hasuno', cardCount: 178 },
 { name: 'hatachu', cardCount: 28 },
 { name: 'Hataya', cardCount: 65 },
 { name: 'Heisuke Kitazawa', cardCount: 1 },
 { name: 'Hideaki Hakozaki', cardCount: 26 },
 { name: 'Hideki Ishikawa', cardCount: 26 },
 { name: 'Hideki Kazama', cardCount: 1 },
 { name: 'Hideyuki Nakajima', cardCount: 2 },
 { name: 'Hikaru Koike', cardCount: 59 },
 { name: 'HiRON', cardCount: 2 },
 { name: 'Hiroaki Ito', cardCount: 1 },
 { name: 'Hiroki Asanuma', cardCount: 21 },
 { name: 'Hiroki Fuchino', cardCount: 8 },
 { name: 'Hiromi Ito', cardCount: 3 },
 { name: 'Hiromichi Sugiyama', cardCount: 23 },
 { name: 'Hironobu Yoshida', cardCount: 1 },
 { name: 'Hiroyuki Sasaki', cardCount: 3 },
 { name: 'Hiroyuki Yamamoto', cardCount: 2 },
 { name: 'Hisao Nakamura', cardCount: 51 },
 { name: 'Hitoshi Ariga', cardCount: 172 },
 { name: 'Hizuki Misono', cardCount: 1 },
 { name: 'hncl', cardCount: 3 },
 { name: 'IKEDA Saki', cardCount: 1 },
 { name: 'Iori Suzuki', cardCount: 1 },
 { name: 'Ito Kyoko', cardCount: 1 },
 { name: 'Iwamoto05', cardCount: 2 },
 { name: 'Izucch', cardCount: 1 },
 { name: 'James Turner', cardCount: 17 },
 { name: 'Jerky', cardCount: 29 },
 { name: 'Jiro Sasumo', cardCount: 15 },
 { name: 'Julie Hang', cardCount: 5 },
 { name: 'Jumpei Akasaka', cardCount: 5 },
 { name: 'Jungo Suzuki', cardCount: 2 },
 { name: 'Junsei Kuninobu', cardCount: 2 },
 { name: 'K. Utsunomiya', cardCount: 12 },
 { name: 'KEIICHIRO ITO', cardCount: 33 },
 { name: 'KIYOTAKA OSHIYAMA', cardCount: 2 },
 { name: 'KYUPIYAMA', cardCount: 2 },
 { name: 'Kagemaru Himeno', cardCount: 240 },
 { name: 'Kai Ishikawa', cardCount: 7 },
 { name: 'Kamome Shirahama', cardCount: 2 },
 { name: 'Kanako Eo', cardCount: 169 },
 { name: 'Kanami Ogata', cardCount: 1 },
 { name: 'kanahei', cardCount: 9 },
 { name: 'kantaro', cardCount: 29 },
 { name: 'Kariya', cardCount: 47 },
 { name: 'Kasumi Matsuda', cardCount: 16 },
 { name: 'Katsunori Sato', cardCount: 1 },
 { name: 'Katsura Tabata', cardCount: 35 },
 { name: 'Katie Gross', cardCount: 1 },
 { name: 'kawayoo', cardCount: 178 },
 { name: 'Kazuma Koda', cardCount: 10 },
 { name: 'Kazumasa Yasukuni', cardCount: 23 },
 { name: 'Kazuaki Aihara', cardCount: 44 },
 { name: 'Kazuki Minami', cardCount: 2 },
 { name: 'Kazuo Yazawa', cardCount: 1 },
 { name: 'Kazuyuki Kano', cardCount: 41 },
 { name: 'Kedamahadaitai Yawarakai', cardCount: 9 },
 { name: 'Keiji Kinebuchi', cardCount: 86 },
 { name: 'Keiko Fukuyama', cardCount: 61 },
 { name: 'Keiko Moritsugu', cardCount: 1 },
 { name: 'Keisin', cardCount: 2 },
 { name: 'Keita Komatsuya', cardCount: 1 },
 { name: 'Ken Ikuji', cardCount: 6 },
 { name: 'Ken Sugimori', cardCount: 1092 },
 { name: 'Kenkichi Toyama', cardCount: 1 },
 { name: 'Kent Kanetsuna', cardCount: 35 },
 { name: 'Kinu Nishimura', cardCount: 1 },
 { name: 'kirisAki', cardCount: 179 },
 { name: 'kodama', cardCount: 61 },
 { name: 'Kouichi Ooyama', cardCount: 88 },
 { name: 'Kouji Tajima', cardCount: 1 },
 { name: 'Kouki Saitou', cardCount: 397 },
 { name: 'Krgc', cardCount: 1 },
 { name: 'Kunihiko Yuyama', cardCount: 2 },
 { name: 'Kurata So', cardCount: 1 },
 { name: 'Kuroimori', cardCount: 2 },
 { name: 'kurumitsu', cardCount: 42 },
 { name: 'Kyoko Koizumi', cardCount: 1 },
 { name: 'Lee HyunJung', cardCount: 10 },
 { name: 'Ligton', cardCount: 10 },
 { name: 'LINNE', cardCount: 10 },
 { name: 'M. Akiyama', cardCount: 2 },
 { name: 'MAHOU', cardCount: 67 },
 { name: 'MARINA Chikazawa', cardCount: 2 },
 { name: 'MINAMINAMI Take', cardCount: 1 },
 { name: 'MPC Film', cardCount: 1 },
 { name: 'MUGENUP', cardCount: 60 },
 { name: 'Maiko Fujiwara', cardCount: 16 },
 { name: 'Makoto Imai', cardCount: 41 },
 { name: 'Makura Tami', cardCount: 1 },
 { name: 'Mana Ibe', cardCount: 6 },
 { name: 'Mark Kraus', cardCount: 1 },
 { name: 'Masa', cardCount: 3 },
 { name: 'Masahiko Ishii', cardCount: 2 },
 { name: 'Masakazu Fukuda', cardCount: 297 },
 { name: 'Masako Tomii', cardCount: 1 },
 { name: 'Masako Yamashita', cardCount: 50 },
 { name: 'Masatoshi Hamada', cardCount: 1 },
 { name: 'May Do', cardCount: 1 },
 { name: 'Megumi Higuchi', cardCount: 3 },
 { name: 'Megumi Mizutani', cardCount: 154 },
 { name: 'Mékayu', cardCount: 14 },
 { name: 'mele', cardCount: 8 },
 { name: 'Meli', cardCount: 1 },
 { name: 'Midori Harada', cardCount: 138 },
 { name: 'Mike Cressy', cardCount: 7 },
 { name: 'Miki Tanaka', cardCount: 112 },
 { name: 'miki kudo', cardCount: 15 },
 { name: 'Mikiko Takeda', cardCount: 1 },
 { name: 'Mikio Menjo', cardCount: 1 },
 { name: 'Milky Isobe', cardCount: 4 },
 { name: 'Mina Akuhara', cardCount: 1 },
 { name: 'Mina Nakai', cardCount: 1 },
 { name: 'Minahamu', cardCount: 1 },
 { name: 'Minato', cardCount: 1 },
 { name: 'mingo', cardCount: 10 },
 { name: 'Miranda Branley', cardCount: 2 },
 { name: 'Mireil', cardCount: 1 },
 { name: 'Misa Tsutsui', cardCount: 22 },
 { name: 'Misaki Hashimoto', cardCount: 8 },
 { name: 'Mitsuhiro Arita', cardCount: 690 },
 { name: 'Miyuki Ogino', cardCount: 1 },
 { name: 'Mizue', cardCount: 63 },
 { name: 'Mochipuyo', cardCount: 1 },
 { name: 'Mori Yuu', cardCount: 1 },
 { name: 'Motofumi Fujiwara', cardCount: 5 },
 { name: 'Mousho', cardCount: 17 },
 { name: 'Mt. TBT', cardCount: 1 },
 { name: 'Mugi Hamada', cardCount: 12 },
 { name: 'NC Empire', cardCount: 105 },
 { name: 'N-DESIGN Inc.', cardCount: 133 },
 { name: 'Nabana Kensaku', cardCount: 1 },
 { name: 'Nabatame Kazutaka', cardCount: 1 },
 { name: 'Nagomi Nijo', cardCount: 18 },
 { name: 'nagano', cardCount: 3 },
 { name: 'nagimiso', cardCount: 84 },
 { name: 'Nakamura Ippan', cardCount: 1 },
 { name: 'Nakaoka', cardCount: 71 },
 { name: 'Naoki Saito', cardCount: 105 },
 { name: 'Naoyo Kimura', cardCount: 38 },
 { name: 'Narano', cardCount: 3 },
 { name: 'Narumi Sato', cardCount: 31 },
 { name: 'Natsu Sato', cardCount: 1 },
 { name: 'Natsuko Shoji été', cardCount: 1 },
 { name: 'Natsumi Miyanose', cardCount: 1 },
 { name: 'Natsumi Yoshida', cardCount: 35 },
 { name: 'Nelnal', cardCount: 12 },
 { name: 'Nisota Niso', cardCount: 19 },
 { name: 'Nobuhiro Imagawa', cardCount: 1 },
 { name: 'Nobusawa', cardCount: 1 },
 { name: 'Nobuyuki Fujimoto', cardCount: 23 },
 { name: 'Nobuyuki Habu', cardCount: 3 },
 { name: 'Noriko Hotta', cardCount: 1 },
 { name: 'Noriko Takaya', cardCount: 1 },
 { name: 'Noriko Uono', cardCount: 1 },
 { name: 'OKACHEKE', cardCount: 39 },
 { name: 'OKUBO', cardCount: 1 },
 { name: 'ORBITALLINK Inc.', cardCount: 2 },
 { name: 'Oswaldo KATO', cardCount: 30 },
 { name: 'Oku', cardCount: 27 },
 { name: 'Ounishi', cardCount: 1 },
 { name: 'Pani Kobayashi', cardCount: 23 },
 { name: 'Peegeray', cardCount: 1 },
 { name: 'PLANETA', cardCount: 16 },
 { name: 'PLANETA Hiiragi', cardCount: 63 },
 { name: 'PLANETA Igarashi', cardCount: 42 },
 { name: 'PLANETA Mochizuki', cardCount: 123 },
 { name: 'PLANETA Otani', cardCount: 48 },
 { name: 'PLANETA Tsuji', cardCount: 59 },
 { name: 'PLANETA Yamashita', cardCount: 13 },
 { name: 'Po-Suzuki', cardCount: 1 },
 { name: 'Q-rais', cardCount: 1 },
 { name: 'REND', cardCount: 21 },
 { name: 'Rhivern', cardCount: 1 },
 { name: 'Reiko Tanoue', cardCount: 10 },
 { name: 'Rond', cardCount: 3 },
 { name: 'Rowan Laidlaw', cardCount: 1 },
 { name: 'Ryo Ueda', cardCount: 128 },
 { name: 'Ryouichi Abe', cardCount: 1 },
 { name: 'Ryota Murayama', cardCount: 8 },
 { name: 'Ryota Saito', cardCount: 2 },
 { name: 'Ryuta Fuse', cardCount: 52 },
 { name: 'Ryuta Kusumi', cardCount: 1 },
 { name: 'SATOSHI NAKAI', cardCount: 3 },
 { name: 'SIE NANAHARA', cardCount: 13 },
 { name: 'Saboteri', cardCount: 1 },
 { name: 'Sachi Matoba', cardCount: 1 },
 { name: 'Sachiko Adachi', cardCount: 38 },
 { name: 'Sachiko Eba', cardCount: 14 },
 { name: 'Saki Hayashiro', cardCount: 42 },
 { name: 'Sakiko Maeda', cardCount: 21 },
 { name: 'Sanosuke Sakuma', cardCount: 137 },
 { name: 'Satoshi Ohta', cardCount: 33 },
 { name: 'Satoshi Shirai', cardCount: 37 },
 { name: 'Saya Tsuruta', cardCount: 104 },
 { name: 'Sayuri Ichiishi', cardCount: 2 },
 { name: 'Scav', cardCount: 1 },
 { name: 'Sekio', cardCount: 77 },
 { name: 'Shiburingaru', cardCount: 10 },
 { name: 'Shibuzoh.', cardCount: 53 },
 { name: 'Shigenori Negishi', cardCount: 15 },
 { name: 'Shimaris Yukichi', cardCount: 1 },
 { name: 'Shin Nagasawa', cardCount: 78 },
 { name: 'Shin-ichi Yoshida', cardCount: 117 },
 { name: 'Shin-ichi Yoshikawa', cardCount: 11 },
 { name: 'Shinji Higuchi', cardCount: 2 },
 { name: 'Shinji Kanda', cardCount: 81 },
 { name: 'Shinya Komatsu', cardCount: 7 },
 { name: 'Shinya Mizuno', cardCount: 2 },
 { name: 'Shizurow', cardCount: 60 },
 { name: 'Souichirou Gunjima', cardCount: 27 },
 { name: 'Studio Bora Inc.', cardCount: 49 },
 { name: 'Sumiyoshi Kizuki', cardCount: 119 },
 { name: 'Susumu Maeya', cardCount: 1 },
 { name: 'Suwama Chiaki', cardCount: 7 },
 { name: 'T. Honda', cardCount: 1 },
 { name: 'TOKIYA', cardCount: 42 },
 { name: 'Taiga Kasai', cardCount: 1 },
 { name: 'Taiga Kayama', cardCount: 1 },
 { name: 'Taira Akitsu', cardCount: 25 },
 { name: 'Takabon', cardCount: 1 },
 { name: 'Takao Unno', cardCount: 2 },
 { name: 'Takashi Yamaguchi', cardCount: 1 },
 { name: 'Takeshi Nakamura', cardCount: 1 },
 { name: 'Takumi Akabane', cardCount: 34 },
 { name: 'Takumi Wada', cardCount: 12 },
 { name: 'Teeziro', cardCount: 16 },
 { name: 'Terada Tera', cardCount: 1 },
 { name: 'Tetsu Kayama', cardCount: 1 },
 { name: 'Tetsuo Hara', cardCount: 1 },
 { name: 'The Pokémon Company Art Team', cardCount: 8 },
 { name: 'Tika Matsuno', cardCount: 28 },
 { name: 'Toyste Beach', cardCount: 29 },
 { name: 'Tomohiro Kitakaze', cardCount: 11 },
 { name: 'Tomokazu Komiya', cardCount: 232 },
 { name: 'Tomomi Kaneko', cardCount: 1 },
 { name: 'Tomomi Ozaki', cardCount: 1 },
 { name: 'Tomowo', cardCount: 1 },
 { name: 'Tonji Matsuno', cardCount: 1 },
 { name: 'Toshinao Aoki', cardCount: 77 },
 { name: 'Tsuyoshi Nagano', cardCount: 1 },
 { name: 'USGMEN', cardCount: 1 },
 { name: 'Uta', cardCount: 24 },
 { name: 'Wataru Kawahara', cardCount: 19 },
 { name: 'Whisker', cardCount: 2 },
 { name: 'Wintr Wandr', cardCount: 1 },
 { name: 'Xime', cardCount: 1 },
 { name: 'YASHIRO Nanaco', cardCount: 1 },
 { name: 'Yano Keiji', cardCount: 12 },
 { name: 'Yasuki Watanabe', cardCount: 1 },
 { name: 'Yoko Hishida', cardCount: 1 },
 { name: 'Yoriyuki Ikegami', cardCount: 6 },
 { name: 'Yoshioka', cardCount: 1 },
 { name: 'Yoshimi Miyoshi', cardCount: 1 },
 { name: 'Yoshinobu Saito', cardCount: 3 },
 { name: 'Yuka Matsubara', cardCount: 1 },
 { name: 'Yuka Morii', cardCount: 194 },
 { name: 'Yukihiro Tada', cardCount: 2 },
 { name: 'Yukiko Baba', cardCount: 108 },
 { name: 'Yumi', cardCount: 91 },
 { name: 'Yuri Umemura', cardCount: 13 },
 { name: 'Yuriko Akase', cardCount: 8 },
 { name: 'Yusuke Ishikawa', cardCount: 14 },
 { name: 'Yusuke Kozaki', cardCount: 2 },
 { name: 'Yusuke Ohmura', cardCount: 26 },
 { name: 'Yusuke Shimada', cardCount: 3 },
 { name: 'Yuu Nishida', cardCount: 85 },
 { name: 'Yuya Oka', cardCount: 7 },
 { name: 'Yuichi Sawayama', cardCount: 1 },
 { name: 'Yuuki Tanaka', cardCount: 1 },
 { name: 'zig', cardCount: 12 },
 { name: 'aoki', cardCount: 75 },
 { name: 'kamonabe', cardCount: 1 },
 { name: 'matazo', cardCount: 18 },
 { name: 'match', cardCount: 25 },
 { name: 'mashu', cardCount: 1 },
 { name: 'miki', cardCount: 2 },
 { name: 'nisimono', cardCount: 7 },
 { name: 'osare', cardCount: 15 },
 { name: 'otumami', cardCount: 21 },
 { name: 'rika', cardCount: 13 },
 { name: 'ryoma uratsuka', cardCount: 25 },
 { name: 'sadaji', cardCount: 14 },
 { name: 'saino misaki', cardCount: 122 },
 { name: 'satoma', cardCount: 1 },
 { name: 'so-taro', cardCount: 54 },
 { name: 'sowsow', cardCount: 125 },
 { name: 'sui', cardCount: 115 },
 { name: 'svlt', cardCount: 2 },
 { name: 'take', cardCount: 13 },
 { name: 'takuyoa', cardCount: 33 },
 { name: 'tetsuya koizumi', cardCount: 24 },
 { name: 'toi8', cardCount: 25 },
 { name: 'tono', cardCount: 17 },
 { name: 'toriyufu', cardCount: 26 },
 { name: 'Uninori', cardCount: 1 },
 { name: 'yuu', cardCount: 42 },
 { name: '2017 Pikachu Project', cardCount: 7 },
 { name: '2019 Pikachu Project', cardCount: 1 },
 { name: 'akagi', cardCount: 27 },
 { name: 'inose yukie', cardCount: 17 },
 { name: 'K. Hoshiba', cardCount: 1 },
 { name: 'Keiji Yano', cardCount: 12 },
 { name: 'takashi shiraishi', cardCount: 2 },
 { name: 'Benimaru Itoh', cardCount: 2 },
 { name: 'M.E. Co., Ltd.', cardCount: 0 },
 { name: 'TOKIYA_GRAPHICS', cardCount: 0 },
 { name: 'sowsow.', cardCount: 0 },
 { name: 'Toyste beach', cardCount: 0 },
 { name: 'Pokémon Art Academy winners', cardCount: 0 },
 { name: 'Tomokazu Komiya(??)', cardCount: 0 },
 { name: 'Tomoaki Imakuni?', cardCount: 0 },
 { name: 'Tomokazu Komiya(self-portrait)', cardCount: 0 },
 { name: 'Shogakukan', cardCount: 0 },
 { name: 'Pokémon Card Fan Club', cardCount: 0 },
 { name: 'MediaFactory', cardCount: 0 },
 { name: 'The Masked Royal', cardCount: 0 },
 { name: 'Tsunekaz Ishihara', cardCount: 0 },
 { name: 'Shuichi]', cardCount: 0 },
 { name: 'Tokiya', cardCount: 0 },
 { name: 'Akabane', cardCount: 0 },
 { name: 'kirisAki(kirisAki)', cardCount: 0 },
 { name: 'kirisAki/Kouki Saitou', cardCount: 0 },
 { name: 'Yusuke Ohmura/others', cardCount: 0 },
 { name: 'Yusuke Murata', cardCount: 0 },
 { name: 'Tomokazu Komiya(Self-portrait)', cardCount: 0 },
 { name: 'Tsunekazu Ishihara', cardCount: 0 },
 { name: 'Sban', cardCount: 0 },
 { name: 'Shogakukan magazines', cardCount: 0 },
 { name: 'Tokiya Sakuba', cardCount: 0 },
 { name: 'Yusuke Ohmura/Others', cardCount: 0 },
 { name: 'Tsunekazu Ishihara/Miki Tanaka', cardCount: 0 },
 { name: 'Tsunekazu Ishihara/CR CG Gangs', cardCount: 0 },
 { name: 'Tsunekazu Ishihara/nagimiso', cardCount: 0 },
 { name: 'Tokiya', cardCount: 0 },
 { name: 'kirisAki', cardCount: 0 },
 { name: 'Tomokazu Komiya/Yusuke Murata', cardCount: 0 },
 { name: 'Yusuke Ohmura/Tomokazu Komiya', cardCount: 0 },
 { name: 'The Pokémon Company', cardCount: 0 },
 { name: 'The Pokémon Company/Media Factory', cardCount: 0 },
 { name: 'Tsunekazu Ishihara and others', cardCount: 0 },
 { name: 'Tsunekazu Ishihara and Miki Tanaka', cardCount: 0 },
 { name: 'Tsunekazu Ishihara and CR CG Gangs', cardCount: 0 },
 { name: 'Tsunekazu Ishihara and nagimiso', cardCount: 0 },
 { name: 'Tokiya', cardCount: 0 },
 { name: 'Akabane and kirisAki', cardCount: 0 },
 { name: 'Tomokazu Komiya and Yusuke Murata', cardCount: 0 },
 { name: 'Yusuke Ohmura and Tomokazu Komiya', cardCount: 0 },
 { name: 'Akiko', cardCount: 0 },
 { name: 'Pokémon Art Academy Winners', cardCount: 0 },
 { name: 'Tomoaki Imakuni', cardCount: 14 },
 { name: 'Shuichi', cardCount: 0 },
 { name: 'The Pokémon Company International', cardCount: 0 },
 { name: 'Pokémon Card Game Illust Grand Prix', cardCount: 0 },
 { name: '2020 Pokémon Card Game Illust Grand Prix', cardCount: 0 },
 { name: '2021 Pokémon Card Game Illust Grand Prix', cardCount: 0 },
 { name: '2022 Pokémon Card Game Illust Grand Prix', cardCount: 0 },
 { name: 'The Pokémon Company International/Creatures Inc.', cardCount: 0 },
 { name: 'Pokémon TCG Card Dex', cardCount: 0 },

]
